# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 15:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_productimage_is_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='dashboard.Address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='dashboard.Billing'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
